#!/bin/sh -e

# Source debconf library
. /usr/share/debconf/confmodule

# Don't ask any questions if upgrading (especially confusing if upgrading
# from versions that pre-date debconf questions and have been setup manually).
# The postinst script won't use the answers unless it's a fresh install.
if [ "$1" = "configure" -a -n "$2" ]; then
    exit 0
fi

# Try to provide a default value based on the current hostname
db_get amppki/fqdn
fqdn="$RET"
if [ -z "$fqdn" ]; then
    db_set amppki/fqdn `hostname --fqdn` || fqdn=`hostname`
fi

# Hostname to generate certificates for
db_input high amppki/fqdn || true
db_go
